#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

$hostname = gethostname();

switch ($hostname) {
    // staging
    case 'proficode':
        define('APP_ENV', 'dev');
        break;

    case 'd228':
        define('APP_ENV', 'live');
        defined('YII_ENV') or define('YII_ENV', 'live');
        break;

    default:
        define('APP_ENV', 'local');
        break;
}

defined('YII_DEBUG') or define('YII_DEBUG', true);

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

$config = \yii\helpers\ArrayHelper::merge(
    require(__DIR__.'/config/console.php'),
    require(__DIR__.'/config/'. APP_ENV . '.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
